# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecomapp', '0004_auto_20190714_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='ecomapp.CartItem'),
        ),
    ]
